import Link from "next/link";
import { HeroEditorMockup } from "@/components/landing/hero-editor-mockup";
import { HERO_MOCKUP_LEFT_PX } from "@/lib/landing-constants";

/**
 * HeroSection
 *
 * Layout strategy:
 *   < 1440px  (mobile / tablet / small desktop): single column, centred — copy then mockup
 *   >= 1440px (Figma canvas):                 absolute positioning inside max-w-[1440px]
 *                                               copy  left = 122px (left-landing-canvas)
 *                                               mockup left = HERO_MOCKUP_LEFT_PX (572px)
 *
 * Typography: all sizes, tracking, leading use design tokens from #95.
 * Layout px values (h-[50px], max-w-[459px] etc.) are Figma frame dimensions,
 * not typography values — out of scope for the #95 token spec. See comments inline.
 *
 * Note on text-landing-label:
 *   This class is generated by BOTH theme.fontSize["landing-label"] (14px/lh/tracking/weight)
 *   AND theme.colors.landing.label (#EDFFD7). Both CSS rules share the class name but set
 *   different properties (font-size vs color), so both apply simultaneously. Intentional.
 */
export function HeroSection() {
  return (
    <section className="w-full pb-16 lg:pb-20 min-[1440px]:pb-24 min-[1440px]:pt-[180px]">
      {/*
        Outer wrapper:
          Default    → flex-col, centred, mockup below copy
          lg (1024px)→ flex-row, copy left / mockup right, px-landing-canvas padding
          1440px     → absolute-positioned children; container is the 1440px anchor
      */}
      <div
        className="
          relative flex flex-col items-center gap-10 px-5 pt-10
          sm:px-8
          lg:flex-row lg:items-center lg:justify-between lg:px-[60px] lg:pt-16 lg:gap-8
          xl:px-landing-canvas
          min-[1440px]:min-h-[590px] min-[1440px]:items-stretch min-[1440px]:px-0 min-[1440px]:pt-0
        "
      >
        {/* ── Copy block ─────────────────────────────────────────────────── */}
        <div
          className="
            relative z-10 w-full text-center
            lg:text-left lg:shrink-0
            min-[1440px]:absolute min-[1440px]:top-0 min-[1440px]:mx-0 min-[1440px]:text-left
            min-[1440px]:left-landing-canvas
          "
          style={{
            // max-w-[459px]: Figma copy-block frame width at 1440px canvas — layout constraint, not a typography token
            maxWidth: "459px",
          }}
        >
          {/*
            text-landing-label applies BOTH:
              - font-size: 14px / line-height: 1 / letter-spacing: -0.48px / font-weight: 700
                (from theme.fontSize["landing-label"])
              - color: #EDFFD7
                (from theme.colors.landing.label)
            The two CSS rules share the class name but set different properties — both apply.
          */}
          <p className="mb-[18px] text-landing-label uppercase tracking-landing-tight">
            Trust commits, not cover letters
          </p>

          {/*
            H1 responsive font-size via tokens:
              mobile  → text-landing-h1-sm (32px / 1.18)
              sm      → text-landing-h1-md (40px / 48px)
              lg      → text-landing-hero  (46px / 54.1px) — at 1440px Figma canvas only
            tracking-landing-h1 (-1.38px) applied at all sizes.
            max-w-[396px]: Figma copy frame inner text-wrap width — layout constraint.
          */}
          <h1
            className="
              mx-auto mb-3.5 max-w-[396px] font-bold text-white tracking-landing-h1
              text-landing-h1-sm
              sm:text-landing-h1-md
              lg:mx-0 lg:text-landing-h1-md
              min-[1440px]:text-landing-hero min-[1440px]:mx-0
            "
          >
            Build together.
            <br />
            Ship Faster.
            <br />
            Contribute with purpose.
          </h1>

          {/*
            text-landing-body: 16px / 25.4px / tracking-[-0.48px] from #95 token.
            max-w-[456px]: Figma body-text frame width — layout constraint.
          */}
          <p className="mx-auto mb-[11px] max-w-[456px] text-landing-body text-white/90 lg:mx-0 min-[1440px]:mx-0">
            func(kode) is an open-source developer platform for the Patch ID community.
            Sign up with GitHub, join collaborative builds, and contribute to projects that matter.
          </p>

          {/*
            gap-landing-cta (47px) at 1440px, standard gap-4 below.
            h-[50px] / min-w-[156px] / min-w-[160px]: Figma CTA button frame dimensions — layout constraints.
          */}
          <div
            className="
              mt-[11px] flex flex-col items-center gap-4
              sm:flex-row sm:flex-wrap sm:justify-center
              lg:justify-start
              min-[1440px]:justify-start min-[1440px]:gap-landing-cta
            "
          >
            {/* Primary CTA — white pill */}
            <Link
              href="/auth/login"
              className="
                inline-flex h-[50px] min-w-[156px] items-center justify-center
                rounded-full bg-white px-6
                text-[15px] font-bold tracking-landing-cta text-black
                transition-transform hover:-translate-y-0.5
              "
            >
              Start Contributing
            </Link>

            {/* Secondary CTA — ghost pill */}
            <Link
              href="/projects"
              className="
                inline-flex h-[50px] min-w-[160px] items-center justify-center
                rounded-full border-2 border-white/[0.13] bg-transparent px-6
                text-[15px] font-bold tracking-landing-cta text-white
                transition-colors hover:bg-white/10
              "
            >
              Explore the project
            </Link>
          </div>
        </div>

        {/* ── Editor mockup ───────────────────────────────────────────────── */}
        {/*
          Below 1440px: normal flex child — no absolute offset (fixes #135).
          At min-[1440px]: absolute + left from HERO_MOCKUP_LEFT_PX via CSS variable
          so the 572px constant is never applied as a bare inline `left` on relative
          positioning (which pushed the mockup off-screen between lg and 1440px).

          max-w-[822px]: Figma mockup frame width — layout constraint.
        */}
        <div
          className="
            z-0 mx-auto w-full max-w-[822px]
            lg:flex-1 lg:mx-0
            min-[1440px]:absolute min-[1440px]:top-0 min-[1440px]:mx-0
            min-[1440px]:w-[822px] min-[1440px]:[left:var(--hero-mockup-left)]
          "
          style={
            {
              ["--hero-mockup-left" as string]: `${HERO_MOCKUP_LEFT_PX}px`,
            } as React.CSSProperties
          }
        >
          <HeroEditorMockup />
        </div>
      </div>
    </section>
  );
}
